### ISSUE TITLE
calling pendant.setProperty from different thread cause exception

### ISSUE THREAD

**Issue by tshikina** [Yaskawa-Global/SmartPendantSDK#2]
Calling pendant.setProperty() from different thread cause exception.

--
Exception occurred:TApplicationException:events failed: out of sequence response: expected 45 but got 36096
--

**Comment by yaskawaglobal** [comment]
Thrift is not thread safe, so it is up-to the client to avoid re-entrancy.  Merged pull request that adds client method synchronization.
