### ISSUE TITLE
build.sh error for yaskawa-ext-2.2.0.jar

### ISSUE THREAD

**Issue by beangao** [Yaskawa-Global/SmartPendantSDK#6]
cd SmartPendantSDK/java
./build.sh

I get a error.
not found yaskawa/ext/api/*.java 

can you tell me how to build yaskawa-ext-2.2.0.jar

**Comment by davidljung** [comment]
You'll need generate the Thrift code first.  Run thrift_gen.sh and it will create those in the api/ folder, then the build will be able to find them.
