### ISSUE TITLE
Cannot locate dlls cSharp

### ISSUE THREAD

**Issue by JurgenKuyper** [Yaskawa-Global/SmartPendantSDK#8]
I generated the thrift data, tried to run dotnet build sdk,csproj /t:build, then this error arises:
CSC : error CS0006: Metadata file 'System.Core.dll' could not be found [C:\Users\Jurgen\source\repos\SmartPendantSDK\csharp\SDK.csproj]
CSC : error CS0006: Metadata file 'Thrift.dll' could not be found [C:\Users\Jurgen\source\repos\SmartPendantSDK\csharp\SDK.csproj]
where can I find those files, they seem to be hardcoded in the SDK.csproj.

**Comment by davidljung** [comment]
Jurgen,
That looks like some issue with your .NET local environment, unrelated to the SDK.  What was the solution?

**Comment by JurgenKuyper** [comment]
the solution was to search for the proper way to embed them in the csproj file. and use a correct dotnet sdk definition (<Project Sdk="Microsoft.NET.Sdk">).
